### ISSUE TITLE
Make User and AuthToken model pluggable

### ISSUE THREAD

**Issue by pupeno** [jazzband/django-rest-knox#159]
[```User``` on line 24](https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L24) is never used and [```model``` on line 39](https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L39) is never used.

If they were used the way the seem to be intended and user was inside the class, this library would be much more flexible and usable in multi-user-model situations.

If this is something you are happy to accept, I can create the PR.

**Comment by johnraz** [comment]
Hello @pupeno, thanks for reaching out.

I see a couple of things that could be improved and match with what DJRF does in the [`TokenAuthentication` class](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L147):

- Have  a configurable `authenticate_header` keyword instead of always using `Token`
- Have a configurable token model instead of being forced to use `AuthToken`

Im' not sure to understand what you mean by "multi-user-model situations" and how having the the User within the class would be of any use?
I don't think we need the user model at all, and this code can probably be removed.

**Comment by pupeno** [comment]
My application has three different classes (and tables) that represent users, one is the normal Django users and the other two are domain specific. Having the user model defined inside the class would allow to do something like this:

```python
class BuyerAuthToken(AuthToken):
    user_model = Buyer

class SellerAuthToken(AuthToken):
    user_model = Seller
```

**Comment by johnraz** [comment]
Ok i see the usecase.
I personally think this is quite niche to use multiple user model.

I need to see a code proposal to decide if the complexity is worth the feature.

I would split it in 2 PRs one for the authentication class and one for the model.

**Comment by pupeno** [comment]
I think the reason it's niche is because Django pushes people in the opposite direction. If it was possible and easier (like it is on other frameworks), more people would do it.

At my company we are now using this library so it'd be great if we can integrate our changes and maintain a single library instead of two separate ones. We are on crunch mode right now, but once that ends (and also we learned more about what works and what doesn't in this auth situation), I'll port the changes back into PRs.

**Comment by johnraz** [comment]
I suggest we don't end up discussing Django's design here, because it will be a rabbit hole.
Let's focus on keeping this library maintainable and in sync with how Django is mainly used.

So as I said, let's decide when we see the code and its complexity.

Good luck with the crunch mode 👍

**Comment by pupeno** [comment]
Done renaming.

Django is actually OK when doing multi-user-model applications (and getting better from what I can see) but I found most libraries expect the single user model situation (understandably so).

**Comment by belugame** [comment]
@pupeno just curious, having the django user model as a base class and your other 2 classes inheriting from them does not work for you?

**Comment by johnraz** [comment]
As exposed in #164, I think we should think about improving the extendability of the `LoginView` as well in order to make the model fully pluggable.

The code below should be part of a dedicated and overridable method, something like `create_auth_token` on the view:
https://github.com/James1345/django-rest-knox/blob/131081373c550db47ab71c7898d19e551efc8655/knox/views.py#L41

Just throwing ideas here, didn't think about it in depth so feel free to tell me if there is a better way.

**Comment by pupeno** [comment]
Yes, I'm doing that. My other user models all inherit from `BaseUserManager` but lots of classes that need a user grab the main user class instead of letting me specify which class to use.

**Comment by johnraz** [comment]
ah oh, I get it now 🤓 I was wondering how that would fit in drk 👍

**Comment by luisroel91** [comment]
Hello? From what I've gathered here, am I correct in understanding that this package does not work with custom user models? Or just...not multiple user models? 

Thanks

**Comment by johnraz** [comment]
Hi there,
This package**works** with custom user models but does **not** work with multiple user models.

**Comment by luisroel91** [comment]
Ahhh, understood. I have never had a need for multiple user models...agree with the above.

Seems like a niche case. 

Thank you!

**Comment by luisroel91** [comment]
I'm a simple guy. I wouldn't feel safe messing with the auth to the degree where you'd have multiple actual user models...I can see the need for multiple users but implementation of multiple ACTUAL user models would be difficult/impossible with Django (AFAIK). That being said what I do know is that in Django you can have multiple user models by "proxy".

Firstly, we can subclass AbstractBaseUser and fill it with our types, then we can map each user with a one to one field so they have the type and all of that types pertinent information/permissions/etc:

`class User(AbstractUser):
    is_usertype1 = models.BooleanField(default=False)
    is_usertype2 = models.BooleanField(default=False)
    is_usertype3 = models.BooleanField(default=False)

class Usertype1(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unique_field1 = models.Charfield()

class Usertype2(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unique_field2 = models.Charfield()

class Usertype3(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unique_field3 = models.Charfield()
`
In Django we already have user permission flags as extra fields (is_admin, is_staff, is_active, etc). 

Why not use these to "type" our users? At some point a user has to signup or an account created for them. It is just a matter of feeding the context to either the view or the serializer and either creating a different view for every type of user we're going to create. That way when we post the user, it will get typed.

For example, posting to /buyers would call a view that has:

`
def get_serializer_context(self):
    context = super().get_serializer_context()
    context['is_buyer'] = True
    return context
`
posting to /sellers would call a view that has:

`
def get_serializer_context(self):
    context = super().get_serializer_context()
    context['foo'] = 'bar'
    return context
`

Just an idea. Not sure if it is absolutely correct/would help you guys with the issue above

**Comment by johnraz** [comment]
I’m going to close this for now as the multi user model seems like a niche use case.
