### ISSUE TITLE
Remove cryptography dependency?

### ISSUE THREAD

**Issue by tasn** [jazzband/django-rest-knox#199]
sha512 is already [in hashlib](https://docs.python.org/3.8/library/hashlib.html) so the cryptography dependency is not really needed. This is especially important since the cryptography dep can be a hassle to setup in some cases (requires a compiler, headers and openssl, as per django-rest-knox docs).

It's a very easy change to make and won't break existing applications as long as they haven't manually set the hash setting and override it to something from cryptography. If they have: this can be a breaking change for a future version.

**Comment by Rotzbua** [comment]
I agree. Seems it was already modernized in #173, but modern python3 does not require this dependency anymore. I created a pr.
