### ISSUE TITLE
Logout using knox gives unauthorized 401 error

### ISSUE THREAD

**Issue by csudharsan** [jazzband/django-rest-knox#207]
urls.py

path('logout', knox_views.LogoutView.as_view())

curl -X POST -w %{http_code} -H 'Authorization: Token c6beb820c2122d9c6dc56e5259479dd6125144d27fb8a27242721d80aaab136e' http://127.0.0.1:8000/api/account/logout
{"detail":"User inactive or deleted."}401

My Settings.py

AUTH_USER_MODEL = 'account.User'
# AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
   'account.backends.CaseInsensitiveModelBackend',
   )

REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
    # ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

from datetime import timedelta
REST_KNOX = {
    'USER_SERIALIZER': 'account.api.serializers.UserSerializer',
    'TOKEN_TTL': timedelta(hours = 24*7),
}

Any idea why i see this error?

**Comment by leonardobarrosdev** [comment]
I already had a similar problem and the solution was to set the **Authorization token** in the Postman headers.
