### ISSUE TITLE
Unpinned Dependency: cryptography

### ISSUE THREAD

**Issue by steverecio** [jazzband/django-rest-knox#244]
An issue with building cryptography will cause the latest build to fail without pinning cryptography<=3.3.2

Details: https://github.com/python-poetry/poetry/issues/3661#issuecomment-776060329

**Comment by lalvarezguillen** [comment]
Further context: https://github.com/pyca/cryptography/issues/5771

**Comment by johnraz** [comment]
cryptography is not used anymore
