### ISSUE TITLE
token_key isn't needed if salt is gone and hashing function is secure

### ISSUE THREAD

**Issue by jonathan-golorry** [jazzband/django-rest-knox#245]
We could remove `token_key` and directly filter the DB by `digest` during authentication.

With the salt gone, I think there are only 2 reasons to search the DB by `token_key` before matching `digest`s.

1. If there isn't a matching `token_key`, the webserver avoids calculating the `digest`.
2. `hmac.compare_digest` prevents timing attacks being used to calculate the `digest`. Timing attacks can calculate the `token_key`, but not the `digest`.

1 shouldn't matter for denial of service attacks because a DB call is being made either way. Webservers can scale until the hash is no longer the limiting factor. Or an attacker could find a `token_key` that exists in the db and start forcing a hash (or potentially multiple, with the current implementation) for each request.

2 shouldn't matter because it would require a near-fully-reversed hashing function just to calculate the tokens needed to continue the timing attack. To calculate the 20th character of the hash, they'd need to calculate 16 different tokens with the same 19-character start to the hash. And once they finally calculated the token's hash, they'd need to reverse that to get a token that could actually be used for authentication.

**Comment by Rotzbua** [comment]
> shouldn't matter for denial of service attacks because a DB call is being made either way. 

The token is used as database index. If there is no equivalent replacement for the index, your change will cause performance problems.

**Comment by jonathan-golorry** [comment]
The digest is the primary key, so it should be indexed in virtually every DB, usually with a clustered index.

**Comment by oaosman84** [comment]
Agree with this. Currently, the code uses token_key and reads all matching `AuthToken`s. If we're not using a custom hash, we can just precompute the digest and do a `.get()` on that and it should be unique.

**Comment by johnraz** [comment]
I still don’t see any added value in removing token_key as I think that avoiding the hashing computation for invalid tokens is a nice performance improvement. I am going to close this one please reopen if you have stronger arguments in favor.
