### ISSUE TITLE
Endpoint for retrieving user by posting token

### ISSUE THREAD

**Issue by csanders7070** [jazzband/django-rest-knox#247]
Hello,

I am trying to find a way to retrieve the user information by posting the token provided by django-knox to some endpoint. I know that I can do the opposite (post user information and get token to pass into headers, etc.), but I can't find anyway to retrieve the user information if all I have is the valid django-knox token. Thanks for the help

christian

**Comment by psibean** [comment]
You should be able to just serialize `request.user` which will be your default user model, just ensure you only include the information you want to send back, e.g. no password

**Comment by csanders7070** [comment]
Thanks so much. That worked exactly as I wanted. Sorry, that was simpler
than I thought.

cas

**Comment by AlexCernik** [comment]
How to create a function to check if user is authenticated??
