### ISSUE TITLE
PR(#272) Replaces code for PR (#275)

### ISSUE THREAD

**Issue by brukberhane** [jazzband/django-rest-knox#286]
As stated in the title, the PR that was most recently merged into the develop branch (#272) that adds the option for token prefixes undoes some of the work done in PR #275. Namely in the `model.py` file, the `AuthTokenManager` class lost it's `**kwargs` parameters so that you can't really populate any custom values to the `AuthToken` custom class you create...

**Comment by johnraz** [comment]
Corresponding MR #287  has been merged, thanks for the fix and sorry for the long delay.
