### ISSUE TITLE
AUTO_REFRESH method never worked

### ISSUE THREAD

**Issue by laksithakumara-cb** [jazzband/django-rest-knox#291]
Hello Know Team, 

I tried this module, and its looks amazing, but I just noticed one thing on this app. its regarding the `Auto Refresh` method. 

`        if auth_token.expiry is not None:
            if auth_token.expiry < timezone.now():
                username = auth_token.user.get_username()
                auth_token.delete()
                token_expired.send(sender=self.__class__,
                                   username=username, source="auth_token")
                return True`

above code line auto delete token if already expired even AUTO_REFRESH = True

**Comment by laksithakumara-cb** [comment]
```
    def _cleanup_token(self, auth_token):
        for other_token in auth_token.user.auth_token_set.all():
            if other_token.digest != auth_token.digest and other_token.expiry:
                if other_token.expiry < timezone.now():
                    other_token.delete()
                    username = other_token.user.get_username()
                    token_expired.send(sender=self.__class__,
                                       username=username, source="other_token")
        if auth_token.expiry is not None:
            if auth_token.expiry < timezone.now():
                username = auth_token.user.get_username()
                auth_token.delete()
                token_expired.send(sender=self.__class__,
                                   username=username, source="auth_token")
                return True
        return False

```

**Comment by laksithakumara-cb** [comment]
This code line should be like this.

`if knox_settings.AUTO_REFRESH == False and auth_token.expiry is not None:`

**Comment by winmorre** [comment]
Can I pick this up?

**Comment by johnraz** [comment]
This has been fixed in current master.
