### ISSUE TITLE
DRF still using sessions after installing and configuring Knox

### ISSUE THREAD

**Issue by uranderu** [jazzband/django-rest-knox#297]
Hi,

I'm trying to use this package to replace my default Django session setup. Specifically to only use this for authentication. I followed the documentation exactly but my login view still sets the csrftoken and sessionid cookie. I tried breaking out sessions completely from my project. But apparently knox depends on it. If you look at the overwritten login view from this [page](https://james1345.github.io/django-rest-knox/auth/):
```
    def post(self, request, format=None):
        serializer = AuthTokenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return super(LoginView, self).post(request, format=None)
```
it uses the "login" function from the "django.contrib.auth" library which is specifically made for sessions. Source code:
```
def login(request, user, backend=None):
    """
    Persist a user id and a backend in the request. This way a user doesn't
    have to reauthenticate on every request. Note that data set during
    the anonymous session is retained when the user logs in.
    """
    session_auth_hash = ""
    if user is None:
        user = request.user
    if hasattr(user, "get_session_auth_hash"):
        session_auth_hash = user.get_session_auth_hash()

    if SESSION_KEY in request.session:
        if _get_user_session_key(request) != user.pk or (
            session_auth_hash
            and not constant_time_compare(
                request.session.get(HASH_SESSION_KEY, ""), session_auth_hash
            )
        ):
            # To avoid reusing another user's session, create a new, empty
            # session if the existing session corresponds to a different
            # authenticated user.
            request.session.flush()
    else:
        request.session.cycle_key()

    try:
        backend = backend or user.backend
    except AttributeError:
        backends = _get_backends(return_tuples=True)
        if len(backends) == 1:
            _, backend = backends[0]
        else:
            raise ValueError(
                "You have multiple authentication backends configured and "
                "therefore must provide the `backend` argument or set the "
                "`backend` attribute on the user."
            )
    else:
        if not isinstance(backend, str):
            raise TypeError(
                "backend must be a dotted import path string (got %r)." % backend
            )

    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
    request.session[BACKEND_SESSION_KEY] = backend
    request.session[HASH_SESSION_KEY] = session_auth_hash
    if hasattr(request, "user"):
        request.user = user
    rotate_token(request)
    user_logged_in.send(sender=user.__class__, request=request, user=user)
```
So when I now authenticate against the login endpoint. I get my token:
![image](https://user-images.githubusercontent.com/71091366/216352477-e25beb50-c2b3-4d5e-a870-3d63bb8b84d6.png)
But the same request also responds with cookies:
![image](https://user-images.githubusercontent.com/71091366/216352562-91d52875-6575-41b7-b016-050875bad65e.png)
This session **can't actually be used** but I still think that it shouldn't be there. It would also save overhead, both in bandwidth and according to the [Django documentation](https://docs.djangoproject.com/en/dev/topics/http/sessions/) for Django itself. "If you don’t want to use sessions, you might as well remove the SessionMiddleware line from [MIDDLEWARE](https://docs.djangoproject.com/en/dev/ref/settings/#std-setting-MIDDLEWARE) and 'django.contrib.sessions' from your [INSTALLED_APPS](https://docs.djangoproject.com/en/dev/ref/settings/#std-setting-INSTALLED_APPS). It’ll save you a small bit of overhead."

**Comment by petenilson** [comment]
What about just removing the `login(request, user)` from the post overwrite? The AuthTokenSerializer does the authentication, so login is just responsible for creating the session, which as you stated is not required.

**Comment by uranderu** [comment]
> What about just removing the `login(request, user)` from the post overwrite? The AuthTokenSerializer does the authentication, so login is just responsible for creating the session, which as you stated is not required.

It has been a year ago since I made this issue. I'm not using this library nor Django anymore. So I can't help any further with this. There also seems to be no (current) intrest in this issue from the developers. So I am closing it.
