### ISSUE TITLE
Package maintenance status

### ISSUE THREAD

**Issue by giovannicimolin** [jazzband/django-rest-knox#303]
Hi @James1345, 

I've noticed this package isn't getting a lot of updates, but it's still widely used by the community.
Would you be open to moving it to JazzBand (https://jazzband.co/about) or open contributions to other developers?

Thanks!

**Comment by James1345** [comment]
Thanks for the message. It certainly looks like this package would benefit
from Jazzband. I'll look at ways of opening it up

**Comment by giovannicimolin** [comment]
This is awesome! Thanks for the quick follow-up on this. 
And let me know if you need a hand maintaining this package, I'm available to help.
