### ISSUE TITLE
Documentation link returns 404

### ISSUE THREAD

**Issue by HansBecker** [jazzband/django-rest-knox#306]
FYI @James1345 , the documentation link https://james1345.github.io/django-rest-knox/ is currently returning a 404.

**Comment by calumy** [comment]
The documentation can now be found at https://jazzband.github.io/django-rest-knox/

Fixed by https://github.com/jazzband/django-rest-knox/pull/305.

**Comment by giovannicimolin** [comment]
@HansBecker Since this was fixed, I'll mark it as complete. Thanks for contributing!
