### ISSUE TITLE
Next release for this package

### ISSUE THREAD

**Issue by dk-WZFinTech** [jazzband/django-rest-knox#320]
When is planned next release of this package.

Are you going to add support for Python 3.11 and Django 4.2?

**Comment by calumy** [comment]
I believe the most recent release already works with Python 3.11 and Django 4.2.

**Comment by dk-WZFinTech** [comment]
> I believe the most recent release already works with Python 3.11 and Django 4.2.

Version available on [PyPI](https://pypi.org/project/django-rest-knox/) is listed with support until Python 3.10

**Comment by Rotzbua** [comment]
Test pass with out problem: https://github.com/jazzband/django-rest-knox/pull/315/checks

**Comment by giovannicimolin** [comment]
@dk-WZFinTech We support the Python 3.11 and Django 4.2, but currently we have no way of creating new pypi releases.

The repository was transferred to JazzBand a few months ago, but we still don't have access to the Pypi Account. I'll try to do something about it in the next week or so. In the meantime, please install directly from GitHub (using a fixed commit).

@Rotzbua Thanks for updating the CI checks, I'll be back to reviewing things starting next week.

**Comment by giovannicimolin** [comment]
@max-wittig Hey! Sorry for the delay with this. 

I had no response from the original package maintainer, so I'll probably end up creating a new Pypi package while the package transfer process is reviewed by Pypi's team.

I'll post an update regarding this on https://github.com/jazzband/django-rest-knox/issues/304.

**Comment by vasilistotskas** [comment]
Any updates on this?

**Comment by johnraz** [comment]
Yes https://github.com/jazzband/django-rest-knox/pull/342

**Comment by johnraz** [comment]
I’m actually going to close in favour of https://github.com/jazzband/django-rest-knox/pull/342 to follow up 😉
