### ISSUE TITLE
Documentation includes mention of deleted token salting

### ISSUE THREAD

**Issue by dgerlanc** [jazzband/django-rest-knox#323]
The documentation includes a setting for `SALT_LENGTH` even though salting was [removed](https://github.com/jazzband/django-rest-knox/pull/193) long ago.

Would be great to remove this reference as it suggests that salting of tokens is still used!

I searched the head of the `develop` branch and could not find a mention of this setting except in the changelog and migrations so I'm not sure why it's showing up in the docs!

See https://jazzband.github.io/django-rest-knox/settings/.

![image](https://github.com/jazzband/django-rest-knox/assets/892459/721ad469-a877-4039-8cbf-e25e870238a9)

**Comment by johnraz** [comment]
This most likely comes from the fact that the gh-pages branch is outdated ... https://github.com/jazzband/django-rest-knox/blob/gh-pages/settings/index.html.

I will mention this in https://github.com/jazzband/django-rest-knox/issues/304

**Comment by giovannicimolin** [comment]
@johnraz @dgerlanc We now have a Ci job that automatically deploys the latest documentation to GH-pages.

https://github.com/jazzband/django-rest-knox/pull/343

**Comment by johnraz** [comment]
@giovannicimolin wonderful doc is up to date now! Closing this one
