### ISSUE TITLE
Doc Question: Where is 'urls(r'api/auth/', include('knox.urls'))'?

### ISSUE THREAD

**Issue by Birddle** [jazzband/django-rest-knox#328]
https://jazzband.github.io/django-rest-knox/urls/#urls-knoxurls
I following doc for install knox, but i don't know which package of `urls`
<img width="393" alt="image" src="https://github.com/jazzband/django-rest-knox/assets/86408260/d725ea82-af38-40b5-8b30-4bd836eae431">

**Comment by luqmansen** [comment]
Is it in here?
https://github.com/luqmansen/django-rest-knox/blob/17e4a5cc1d74113b77b3b2a295afa50b320d65aa/knox_project/urls.py#L1-L8

**Comment by giovannicimolin** [comment]
@Birddle Ah, I think I know what you mean: are you confused about where the `urls` method is coming from? 

Newer django versions use the `include` method, like this:
```
from django.urls import include

urlpatterns = [
    ....
    # Knox URLs
    path("auth/", include("knox.urls")),
]
```

Reference:
* [Including other URLconfs](https://docs.djangoproject.com/en/5.0/topics/http/urls/#including-other-urlconfs)


_Note:_ if you have some time, can you contribute this small update to the documentation?
