### ISSUE TITLE
Query Regarding Stable Branch for Production Use

### ISSUE THREAD

**Issue by Kanellaman** [jazzband/django-rest-knox#331]
Hello Knox Team,

I hope this message finds you well. I am planning to use Knox in a production environment and I understand that there have been some recent updates and fixes that might not yet be reflected in the latest release available on PyPI.

Given the importance of stability and security for production environments, I would like to inquire about the following:

- **Stable Branch**: Could you please confirm which branch of the Knox repository is considered stable and safe for production use?

- **Recommended Practices**: If there are any specific commits or tags that you recommend for a stable production environment, please let me know. Additionally, if there are particular precautions or additional steps I should take when using the code directly from GitHub, I would greatly appreciate your guidance.

I understand the challenges involved in maintaining open-source projects, and I want to express my gratitude for your work on Knox.

**Comment by johnraz** [comment]
This project being community driven and with a small amount of contributors, stability cannot be guaranteed and using this in production comes at your own risk.

That being said, we release to pypi from tags and those tags are stamped on master… This means that using master should be considered « stable » in the sense that we merged code there we believed would work.

There is no extensive testing (the unit test suite is quite minimal) or QA being done on this repository AFAIK.
