### ISSUE TITLE
Social auth support #NotAnIssue

### ISSUE THREAD

**Issue by spinxi** [jazzband/django-rest-knox#332]
**### THIS IS NOT AN ISSUE**

So, I'm really new from django-allauth with microsoft graph social auth, 

I reacreated my project with DRF, therefore I need rest auth too, and I wanna know if this library supports social auth too cause I use microsoft graph.
In documentations I can't find one, so could you guys help me in this situation?

**Comment by johnraz** [comment]
This seems to be covered in https://github.com/jazzband/django-rest-knox/issues/257

I believed it’s not covered by the documentation because we don’t guarantee it will always work 🤓
