### ISSUE TITLE
Return custom response when invalid token is given

### ISSUE THREAD

**Issue by Tom5421** [jazzband/django-rest-knox#349]
Hi,

Is it possible to return a custom response/http response code when an invalid token is sent?

Thanks
Tom

**Comment by johnraz** [comment]
Yes you could define your own flavor of `TokenAuthentication ` https://github.com/jazzband/django-rest-knox/blob/01c1de4f625dd0ce752eadc7da1371f6ed5fa58e/knox/auth.py#L17 and use that instead.

From there it's pure DRF configuration (example of usage of that class can be seen at https://github.com/jazzband/django-rest-knox/blob/01c1de4f625dd0ce752eadc7da1371f6ed5fa58e/knox_project/views.py#L1-L13)
