### ISSUE TITLE
Python 3.12 and django 5.0 compatibility

### ISSUE THREAD

**Issue by cloutierjo** [jazzband/django-rest-knox#350]
Reading from the release note and issue here, it is unclear how to install a version of this project that is compatible with actual release of python and django. I've seen recommandation of installing direclty from git, but also that installing from git is not QAed and thus not production safe. Current officially suported django release is 4.0 whih has been EOL for more than a year. 

I see in the commit tha https://github.com/jazzband/django-rest-knox/pull/321 added support for those version, but without official release, installing a critical component like knox from the devlop branch seems to be a bit risky.

**Comment by johnraz** [comment]
You can track the new relase here https://github.com/jazzband/django-rest-knox/pull/342
