### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'KNOX_TOKEN_MODEL'

### ISSUE THREAD

**Issue by Spawin** [jazzband/django-rest-knox#359]
There is an error when trying to migrate after adding **Knox 5.0.0**.
This comes from `site-packages\knox\migrations\0001_initial.py", line 12` because we are trying to recover `settings.KNOX_TOKEN_MODEL` which according to the documentation is optional ([Settings](https://jazzband.github.io/django-rest-knox/settings/)).

**Comment by Spawin** [comment]
> https://github.com/jazzband/django-rest-knox/blob/develop/knox/settings.py#L19
> 
> There is a typo in the line above, the defaults dictionary key should be fixed, @Spawin can you open a PR ?

The problem is that in the migration we use the global settings `from django.conf import settings` .

**Comment by johnraz** [comment]
Then I guess the proper fix is to use the right settings module ☺️

**Comment by giovannicimolin** [comment]
@johnraz Here's a PR to fix this: https://github.com/jazzband/django-rest-knox/pull/360

Can you review?

**Comment by johnraz** [comment]
@giovannicimolin approved thanks ! 🙏

**Comment by giovannicimolin** [comment]
@johnraz Thanks for the review.

@Spawin Can you test with https://pypi.org/project/django-rest-knox/5.0.1/ and close the issue if your issues are fixed?
